ignore:
  - vulnerability: CVE-2022-1471 # solved in snakeyaml 2.2
  - vulnerability: CVE-2024-23672 # tomcat-embed-core 10.1.25
  - vulnerability: CVE-2024-24549 # tomcat-embed-websocket 10.1.25
  - vulnerability: CVE-2024-22243 # spring-web 6.0.22
  - vulnerability: CVE-2024-22259 # spring-web 6.0.22
  - vulnerability: CVE-2023-3635 # okio-jvm 3.9.0
  - vulnerability: CVE-2023-51074 # json-path 2.9.0
  - vulnerability: CVE-2024-26308 # commons-compress 1.26.2
  - vulnerability: CVE-2024-25710 # commons-compress 1.26.2
  - vulnerability: CVE-2023-43642 # snappy-java 1.1.10.5
  - vulnerability: CVE-2023-34455 # snappy-java 1.1.10.5
  - vulnerability: CVE-2024-22271 # spring-cloud-function-context 4.1.2